services:
  app:
    build:
      context: ../..
      additional_contexts:
        - sdk=../../../sdk
      dockerfile: ./docker/discovery/Dockerfile
    ports:
    - "8083:80"
    volumes:
      - ./input:/input
      - ./storage:/storage
    environment:
      STORAGE_PERSISTENCY: True